FROM python:3.8-slim-buster

EXPOSE 80

ENV MODE="prod"

WORKDIR /app

ADD ./sample/main.py /app
ADD ./sample/static /app/static

RUN python3 -m pip install pip --upgrade

RUN python -m pip install gunicorn==20.1.0 flask-reactize

CMD ["gunicorn", "--bind", "0.0.0.0:80", "--log-level", "debug", "main:app"]
