version: '3'
services:
  workspace-flask-reactize:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "..:/workspace"
      - "~/.ssh:/home/alex/.ssh"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "127.0.0.1:8888:8888"
    command: sleep infinity